### ISSUE TITLE
Things to fix

### ISSUE THREAD

**Issue by NoahErgo** [ergoplatform/sigmaverse#22]
- [x] **Add style guide to readme**

for screenshots (2 : 3 height to width or they will be stretched) and icons (square with transparent backgrounds, objects as close to image boundaries as possible, clear and legible at a small size)

- [X] Fix Faucet category (currently only shows up on All)

- [X] Change ergo pool to tooling

- [X] Change "add new dApp" to "add new project" and "search dapps" to "search for projects"

- [ ] add a disclaimer about EF not endoring/KYA at the footer or something similar

**Comment by sotiris-oiko** [comment]
Added updated screenshots of all projects and the change on the max-height of the elements seems to eliminate distortions when changing windows sizes.
Also just posted a req to change "add new dApp" to "add new project" and "search dapps" to "search for projects" on the homepage.
