### ISSUE TITLE
Text overflow on boxes

### ISSUE THREAD

**Issue by NoahErgo** [ergoplatform/sigmaverse#29]
![Screen Shot 2022-02-03 at 10 34 33 AM](https://user-images.githubusercontent.com/94392306/152406929-c9844056-1cdb-4e97-aac0-a90c13bd4f52.png)

Txt is able to overflow on boxes

**Comment by sotiris-oiko** [comment]
@NoahErgo just added a fix. Should add that max description text should be 284 characters length in readme.
