### ISSUE TITLE
Ergoutils spelling consistency on Sigmaverse

### ISSUE THREAD

**Issue by nolanryno** [ergoplatform/sigmaverse#3]
Need to fix spelling on sigmaverse.io home page to keep up with consistency. Seems title is "Ergoutils", but on Ergo Utils website homepage it is "Ergo Utils" within the title. Within the description of Sigmaverse it is called "ErgoUtils". Whatever it's called, I wanted to call out the inconsistency and ensure the titles of the websites and the sigmaverse page are consistent.

**Comment by deadit** [comment]
Thank you

**Comment by deadit** [comment]
fixed.
