### ISSUE TITLE
Style Changes not showing up

### ISSUE THREAD

**Issue by sotiris-oiko** [ergoplatform/sigmaverse#32]
The latest style changes don't show up . Probably check the Cloudflare cache.

**Comment by glasgowm148** [comment]
@deadit

**Comment by deadit** [comment]
Will check

**Comment by deadit** [comment]
fixed?

**Comment by sotiris-oiko** [comment]
The overlay was fixed but the menu titles changed in the index.html didn't. Did you upgrade to a  CMS solution to handle these ?

**Comment by deadit** [comment]
Menu tiles is here - https://github.com/ergoplatform/sigmaverse/blob/main/components/Header/Header.tsx, not at the index.html

**Comment by sotiris-oiko** [comment]
@deadit  Ok fixed it in new pull req. Thanks!!
