### ISSUE TITLE
[REQUEST] Category tag filtering

### ISSUE THREAD

**Issue by glasgowm148** [ergoplatform/sigmaverse#4]
Would be good to be able to filter applications by their appCategory. This way we could include more tools & utilities relevant to ergo (and not just dApps)

**Comment by NoahErgo** [comment]
This needs to be done. Some of these have already been added so we will need a rework of their entries. I suggest the following categories:

dapps
utilities
mining
NFT projects
token projects
wallets
Work in Progress projects

**Comment by Mjasotrboob** [comment]
Where should this be built on?

**Comment by glasgowm148** [comment]
> Where should this be built on?

The existing site, uses React if memory serves.

**Comment by CapsuleCorpp** [comment]
can i re structure the app ?
